<script setup>
import { Head, router, useForm, usePage } from '@inertiajs/vue3';
import { computed, ref } from 'vue';
const props = defineProps({ students: Array, faculties: Array, studyPrograms: Array });
const page = usePage(); const editingId = ref(null);
const form = useForm({ nim:'', name:'', faculty_id:'', study_program_id:'', entry_year:'', is_active:true });
const availablePrograms = computed(() => props.studyPrograms.filter(p => String(p.faculty_id) === String(form.faculty_id)));
function reset(){editingId.value=null;form.reset();form.clearErrors();form.is_active=true;}
function edit(item){editingId.value=item.id;form.nim=item.nim;form.name=item.name;form.faculty_id=item.faculty_id ?? '';form.study_program_id=item.study_program_id ?? '';form.entry_year=item.entry_year ?? '';form.is_active=item.is_active;form.clearErrors();}
function facultyChanged(){form.study_program_id='';}
function submit(){const opts={onSuccess:reset};editingId.value?form.put(`/master/mahasiswa/${editingId.value}`,opts):form.post('/master/mahasiswa',opts);}
function remove(item){if(confirm(`Hapus mahasiswa "${item.name}"?`))router.delete(`/master/mahasiswa/${item.id}`);}
</script>
<template><Head title="Master Mahasiswa"/><main class="min-h-screen bg-slate-50 p-6 text-slate-900 sm:p-10"><div class="mx-auto max-w-7xl"><a href="/dashboard" class="text-sm font-semibold text-indigo-700">← Dashboard</a><h1 class="mt-4 text-2xl font-bold">Master Mahasiswa</h1><p class="mt-1 text-sm text-slate-600">Data identitas mahasiswa. Program studi dibatasi sesuai fakultas.</p><p v-if="page.props.flash?.success" class="mt-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">{{page.props.flash.success}}</p><p v-if="page.props.flash?.error" class="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-800">{{page.props.flash.error}}</p>
<div class="mt-6 grid gap-6 lg:grid-cols-2"><form @submit.prevent="submit" class="space-y-4 rounded-xl border bg-white p-5"><h2 class="font-semibold">{{editingId?'Ubah mahasiswa':'Tambah mahasiswa'}}</h2><label class="block text-sm font-medium">NIM<input v-model="form.nim" required maxlength="50" class="mt-1 w-full rounded-lg border p-2.5"/><span class="text-sm text-red-700">{{form.errors.nim}}</span></label><label class="block text-sm font-medium">Nama mahasiswa<input v-model="form.name" required maxlength="255" class="mt-1 w-full rounded-lg border p-2.5"/><span class="text-sm text-red-700">{{form.errors.name}}</span></label><label class="block text-sm font-medium">Fakultas<select v-model="form.faculty_id" @change="facultyChanged" class="mt-1 w-full rounded-lg border p-2.5"><option value="">Belum ditentukan</option><option v-for="f in faculties" :key="f.id" :value="f.id">{{f.name}}</option></select><span class="text-sm text-red-700">{{form.errors.faculty_id}}</span></label><label class="block text-sm font-medium">Program studi<select v-model="form.study_program_id" :disabled="!form.faculty_id" class="mt-1 w-full rounded-lg border p-2.5"><option value="">Belum ditentukan</option><option v-for="p in availablePrograms" :key="p.id" :value="p.id">{{p.name}}</option></select><span class="text-sm text-red-700">{{form.errors.study_program_id}}</span></label><label class="block text-sm font-medium">Tahun masuk<input v-model="form.entry_year" type="number" min="1900" max="2200" class="mt-1 w-full rounded-lg border p-2.5"/><span class="text-sm text-red-700">{{form.errors.entry_year}}</span></label><label class="flex items-center gap-2 text-sm"><input v-model="form.is_active" type="checkbox"/> Aktif</label><div class="flex gap-2"><button :disabled="form.processing" class="rounded-lg bg-indigo-700 px-4 py-2 text-sm font-semibold text-white">Simpan</button><button v-if="editingId" type="button" @click="reset" class="rounded-lg border px-4 py-2 text-sm">Batal</button></div></form>
<section class="overflow-hidden rounded-xl border bg-white"><div class="border-b p-5 font-semibold">Daftar mahasiswa ({{students.length}})</div><p v-if="!students.length" class="p-6 text-sm text-slate-500">Belum ada data mahasiswa.</p><div v-for="item in students" :key="item.id" class="flex items-center justify-between gap-3 border-b p-4 last:border-0"><div class="min-w-0"><p class="font-semibold">{{item.name}}</p><p class="text-sm text-slate-500">{{item.nim}} · {{item.faculty?.name || 'Fakultas belum diisi'}} · {{item.study_program?.name || 'Program studi belum diisi'}} · {{item.entry_year || 'Tahun masuk —'}} · {{item.is_active?'Aktif':'Nonaktif'}}</p></div><div class="flex shrink-0 gap-2"><button @click="edit(item)" class="rounded border px-3 py-1.5 text-sm">Ubah</button><button @click="remove(item)" class="rounded border border-red-200 px-3 py-1.5 text-sm text-red-700">Hapus</button></div></div></section></div></div></main></template>
